# Generated by Django 5.2.6 on 2026-03-25 12:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='external_ai_api', max_length=32)),
                ('external_endpoint', models.URLField(blank=True)),
                ('external_api_key', models.CharField(blank=True, max_length=512)),
                ('external_model', models.CharField(blank=True, max_length=128)),
                ('external_timeout_ms', models.PositiveIntegerField(default=20000)),
                ('external_system_prompt', models.TextField(blank=True)),
                ('external_user_prompt_template', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI配置',
                'verbose_name_plural': 'AI配置',
            },
        ),
        migrations.CreateModel(
            name='SkinAnalysisRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('provider', models.CharField(default='external_ai_api', max_length=32)),
                ('diagnosis', models.CharField(blank=True, max_length=255)),
                ('probability', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('image_sha256', models.CharField(max_length=64)),
                ('request_source', models.CharField(default='app', max_length=32)),
                ('remote_addr', models.GenericIPAddressField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '识别记录',
                'verbose_name_plural': '识别记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
