# Generated by Django 5.2.6 on 2026-03-29 15:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkinRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('provider', models.CharField(default='external_ai_api', max_length=32)),
                ('photo_clarity', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('photo_lighting', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('photo_composition', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('skin_overall', models.CharField(blank=True, max_length=32)),
                ('skin_moisture', models.CharField(blank=True, max_length=32)),
                ('skin_texture', models.CharField(blank=True, max_length=32)),
                ('skin_issues', models.JSONField(blank=True, default=list)),
                ('observations', models.JSONField(blank=True, default=list)),
                ('suggestions', models.JSONField(blank=True, default=list)),
                ('user_note', models.TextField(blank=True)),
                ('user_tags', models.JSONField(blank=True, default=list)),
                ('image_sha256', models.CharField(max_length=64)),
                ('request_source', models.CharField(default='app', max_length=32)),
                ('remote_addr', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '皮肤状态记录',
                'verbose_name_plural': '皮肤状态记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='aiproviderconfig',
            name='external_skin_record_system_prompt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aiproviderconfig',
            name='external_skin_record_user_prompt_template',
            field=models.TextField(blank=True),
        ),
    ]
